# Generated by Django 4.1 on 2023-12-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tareas',
            table='tareas',
        ),
    ]
