# Generated by Django 4.1 on 2023-12-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0002_alter_tareas_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipousuarios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='authpermission',
            table='auth_permission',
        ),
        migrations.AlterModelTable(
            name='authuser',
            table='auth_user',
        ),
        migrations.AlterModelTable(
            name='authusergroups',
            table='auth_user_groups',
        ),
        migrations.AlterModelTable(
            name='authuseruserpermissions',
            table='auth_user_user_permissions',
        ),
        migrations.AlterModelTable(
            name='djangoadminlog',
            table='django_admin_log',
        ),
        migrations.AlterModelTable(
            name='djangocontenttype',
            table='django_content_type',
        ),
        migrations.AlterModelTable(
            name='djangomigrations',
            table='django_migrations',
        ),
        migrations.AlterModelTable(
            name='djangosession',
            table='django_session',
        ),
        migrations.AlterModelTable(
            name='horasdedicadastareas',
            table='horasdedicadastareas',
        ),
        migrations.AlterModelTable(
            name='proyectos',
            table='proyectos',
        ),
    ]
