# Generated by Django 4.1 on 2023-10-29 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserTasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoproyectos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipousuarios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': True},
        ),
    ]
